# Generated by Django 3.2 on 2021-07-07 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(default=0)),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BingoCardCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories_created', to='api.siteuser')),
            ],
        ),
        migrations.CreateModel(
            name='BingoCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_timestamp', models.FloatField(default=0)),
                ('best', models.FloatField(default=0)),
                ('hot', models.FloatField(default=0)),
                ('ups', models.IntegerField()),
                ('votes_total', models.IntegerField()),
                ('score', models.IntegerField()),
                ('tile_1', models.CharField(max_length=200)),
                ('tile_2', models.CharField(max_length=200)),
                ('tile_3', models.CharField(max_length=200)),
                ('tile_4', models.CharField(max_length=200)),
                ('tile_5', models.CharField(max_length=200)),
                ('tile_6', models.CharField(max_length=200)),
                ('tile_7', models.CharField(max_length=200)),
                ('tile_8', models.CharField(max_length=200)),
                ('tile_9', models.CharField(max_length=200)),
                ('tile_10', models.CharField(max_length=200)),
                ('tile_11', models.CharField(max_length=200)),
                ('tile_12', models.CharField(max_length=200)),
                ('tile_13', models.CharField(max_length=200)),
                ('tile_14', models.CharField(max_length=200)),
                ('tile_15', models.CharField(max_length=200)),
                ('tile_16', models.CharField(max_length=200)),
                ('tile_17', models.CharField(max_length=200)),
                ('tile_18', models.CharField(max_length=200)),
                ('tile_19', models.CharField(max_length=200)),
                ('tile_20', models.CharField(max_length=200)),
                ('tile_21', models.CharField(max_length=200)),
                ('tile_22', models.CharField(max_length=200)),
                ('tile_23', models.CharField(max_length=200)),
                ('tile_24', models.CharField(max_length=200)),
                ('tile_25', models.CharField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bingo_cards', to='api.siteuser')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='api.bingocardcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up', models.BooleanField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.bingocard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.siteuser')),
            ],
            options={
                'unique_together': {('user', 'card')},
            },
        ),
    ]
