#!/usr/bin/env python3

# https://djangocentral.com/deploy-django-with-nginx-gunicorn-postgresql-and-lets-encrypt-ssl-on-ubuntu/

import requests
from subprocess import run
from db_name import STATICFILES_DIRS, STATIC_URL, APP_NAME

resp = requests.get("https://api.ipify.org?format=json")
ip = resp.json()["ip"]

server_conf = f"""

server {{
    listen 80;
    server_name {ip};

    location = /favicon.ico {{  access_log off; log_not_found off;  }}
    location {STATIC_URL} {{
        root {STATICFILES_DIRS[0].parent};
    }}

    location / {{
        include proxy_params;
        proxy_pass http://unix:/run/gunicorn.sock;
    }}
}}

"""

conf_filename = f"{APP_NAME}.conf"

with open(conf_filename, "w") as f:
    f.write(server_conf)

run(f"sudo rm /etc/nginx/sites-available/default", shell=True)
run(f"sudo mv {conf_filename} /etc/nginx/sites-available/", shell=True)
run(
    f"sudo ln -s /etc/nginx/sites-available/{conf_filename} /etc/nginx/sites-enabled",
    shell=True,
)
result = run("sudo nginx -t", shell=True, capture_output=True)

if result.stderr:
    print(result.stderr)

run("sudo systemctl restart nginx", shell=True)
