#!/usr/bin/env python3

import os
from subprocess import run
from db_name import db_name
from decouple import config

usr = os.getlogin()

sql = f'''

CREATE DATABASE {db_name};
CREATE USER {usr} WITH PASSWORD '{config("DB_PASS")}';
ALTER ROLE {usr} SET client_encoding TO 'utf8';
ALTER ROLE {usr} SET default_transaction_isolation TO 'read committed';
ALTER ROLE {usr} SET timezone TO 'UTC';
GRANT ALL PRIVILEGES ON DATABASE {db_name} TO {usr};

'''

result = run(f'echo "{sql}" | sudo -u postgres psql --file -', shell=True, text=True, capture_output=True)

if result.stderr:
    print(result.stderr)
else:
    run('scripts/fill-db', shell=True)
